<?php
namespace Magenest\Rules\Model\ResourceModel\Rule;

use Magenest\Rules\Model\Rule;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{

    /**
     * Define resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(Rule::class, \Magenest\Rules\Model\ResourceModel\Rule::class);
    }
    public function getItems()
    {
        $this->addFieldToSelect('*')->addFieldToFilter('status',['eq'=>'pending']);
        return parent::getItems(); // TODO: Change the autogenerated stub
    }

}
